version: "3.9"

services:
  bot:
    image: ghcr.io/niclassslua/unimannheim-bib-discord-bot:main
    pull_policy: always
    container_name: unimannheim-bib-bot
    env_file:
      - .env
    environment:
      NODE_ENV: production
      TZ: Europe/Berlin
      USE_DB: "false"
    restart: unless-stopped
